### PR TITLE
Update runtime, update avahi, change boost location, change hash of vpl3

### LINKED ISSUE #6: update KDE runtime to 5.15

### PR DESCRIPTION
**Pull request by lionirdeadman**
Update runtime to 5.15 since 5.12 is EOL
Use QtWebEngine.BaseApp as needed
Bintray no longer hosts boost therefore using jfrog
Hash of vpl3 changed, not sure why.

Fix #6

### CODE REVIEW

**Comment by hfiguiere** [comment]
I'd remove the `flathub.json` since it's empty.

**Comment by mbonani** [comment]
Thank for trying to update, but there is a problem with 5.15 that our real robot aren't detected on normal usb/com port. We have to investigate.

**Comment by mbonani** [comment]
our PR on our repo: https://github.com/Mobsya/aseba/pull/882

**Comment by lionirdeadman** [comment]
Ah, that's unfortunate. :(

It seems upstream already had all the other changes too. Kinda wish I had noticed, haha.

**Comment by mbonani** [comment]
will be implemented

**Pull request closed without merging**
